[package]
name = "alua"
version = "0.1.0"
edition = "2021"
description = "A Rust library for generating lua lsp annotations from Rust types"
repository = "https://github.com/eievui5/alua"
licnese-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alua-macros = { version = "0.1.0", path = "alua-macros" }
