[package]
name = "alua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alua-macros = { version = "0.1.0", path = "alua-macros" }
